
version: '3'

services:
  postgres:
    image: library/postgres:11.14
    environment:
      POSTGRES_DB: "antorus"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
    - /home/:/home/
  web:
    build: .
    command: >
      bash -c "
      python manage.py makemigrations
      & python manage.py migrate
      & python manage.py runserver 0.0.0.0:8080
      "
    volumes:
      - .:/code/
      - /var/www/antorus/media/:/code/media/
    ports:
      - "8080:8080"
    depends_on:
      - postgres