
version: '3'

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "antorus"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/antorus
      - /var/www/antorus/media/:/code/media/
    ports:
      - "8080:8080"
    depends_on:
      - postgres