version: '3'

services:
  antorus:
    build: .
    expose:
      - "8000"
    env_file:
      - antorus/.env
    volumes:
      - antorus_static:/opt/antorus/static
      - antorus_media:/opt/antorus/media
      - ./main/migrations/:/opt/antorus/main/migrations/:rw
      - ./logs:/opt/antorus/logs
    depends_on:
      - antorus_db
    networks:
     - antorus_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - antorus_static:/data/static
      - antorus_media:/data/media
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - antorus
    restart: always
    networks:
      - antorus_network

  antorus_db:
    image: postgres:16-alpine
    env_file:
      - antorus/.env
    expose:
      - 5432
    networks:
      - antorus_network

  certbot:
    image: certbot/cerbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  antorus_network:

volumes:
  antorus_static:
  antorus_media: