from django.urls import path
from . import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<slug:slug>/', views.product, name='product'),
    path('category/<slug:category>/<slug:subcategory>/', views.subcategory, name='subcategory'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('createOrder/', views.create_order),
    path('cartService/', views.cart_service),
    path('checkCoupon/', views.check_coupon),
    path('faq/', views.faq, name='faq'),
    path('privacyPolicy/', views.privacy_policy, name='privacyPolicy'),
    path('termsOfService/', views.terms_of_service, name='termsOfService'),
    path('myAccount/', views.my_account, name='my_account'),
    path('resetPassword/', views.reset_password, name='reset_password'),
    path('accountDetails/', views.account_details, name='account_details'),
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
    path('orders/', views.orders, name='orders'),
    path('order/<int:pk>/', views.order, name='order'),
    path('changeDetails/', views.change_account_details, name='changeDetails'),
    path('createAccount/', views.create_account, name='createAccount'),
    path('checkEmail/<str:token>/', views.check_auth_token, name='checkEmail'),
    path('generatePassword/', views.send_new_password, name='generatePassword'),
    path('searchProduct/', views.search_products),
    path('result/<str:search>/', views.search_result, name='result'),
    path('pisioCallback/', views.plisio_callback, name='plisio'),
    path('successOrder/', views.success_order, name='success_order'),
    path('stripe/', views.stripe, name='stripe'),
    path('stripe_create_payment/', views.stripe_create_payment, name='stripe_payment'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path('404/', TemplateView.as_view(template_name="404.html"), name='404'),
]
